name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls
          echo
          pwd
          pip install -r requirements.test.txt

      - name: Run pytest
        env:
          DATABASE_PATH: ${{vars.DATABASE_PATH}}
          DATABASE_DRIVER: ${{vars.DATABASE_DRIVER}}
        run: pytest tests/


  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff linter
        run: ruff check src/


  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install isort
        run: pip install isort

      - name: Run isort linter
        run: isort --check-only  --profile=black src/


  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install mypy
        run: pip install -r requirements.test.txt

      - name: Run mypy type checking
        run: mypy src/